/**
 * @description The OpenCode plugin the bot loads into every `opencode serve` it
 * starts, so a compaction OpenCode runs ON ITS OWN when the context overflows
 * also tells the next session which skills to load again.
 *
 * WHY this exists: the loaded-skills guidance rides the bot's per-invocation
 * `instruction` (`POST /session/:id/summarize`), which an overflow compaction
 * never receives, and unlike D3 it is not baked into the fork's prompt. OpenCode
 * runs the plugin hook `experimental.session.compacting` before EVERY compaction
 * (manual and overflow) and appends the strings a plugin pushes into
 * `output.context` to the compaction prompt. A plugin needs no fork rebuild.
 *
 * The plugin is a generated file in `DATA_DIR`, rewritten on every server start so
 * it always carries the current guidance text, and it reaches the server through
 * `OPENCODE_CONFIG_CONTENT` — a config source OpenCode MERGES with the user's own
 * (plugin lists are concatenated, so the user's plugins stay loaded and their
 * config file is never written).
 *
 * The hook only sees the session id, never the bot's per-invocation instruction,
 * so it cannot skip a compaction that already carries the guidance. The bot
 * therefore leaves the skills guidance out of its instruction when the server has
 * this plugin ({@link checkHasOpenCodeCompactPlugin} over `GET /config`), and keeps
 * it for a server the bot did not start.
 */

import fs from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';
import { compactionSkillsGuidance } from './compactOnIdle';

/** File name of the generated plugin inside `DATA_DIR`; also how the bot recognises it in `GET /config`. */
export const openCodeCompactPluginFileName = 'telegramcode-compaction-plugin.mjs';

/** OpenCode requires a path plugin to export an id. */
export const openCodeCompactPluginId = 'telegramcode-compaction';

/**
 * @description The text the plugin adds to every compaction prompt. OpenCode
 * appends it AFTER the bot's per-invocation instruction, which may end with the
 * F2 closing-section directive ("write nothing after the end marker"), so the text
 * says outright that the skills list belongs inside the summary.
 */
export function getOpenCodeCompactPluginContext(): string {
  return `Additional instruction for the summary itself (put it inside the summary, never after a closing section the instructions above require): ${compactionSkillsGuidance}`;
}

/** @description The plugin module source: a v1 plugin (`default` export with `id` + `server`). */
export function buildOpenCodeCompactPluginSource(context: string): string {
  return [
    '// Generated by TelegramCode on every OpenCode server start. Do not edit.',
    `const context = ${JSON.stringify(context)};`,
    'export default {',
    `  id: ${JSON.stringify(openCodeCompactPluginId)},`,
    '  server: async () => ({',
    '    "experimental.session.compacting": async (_input, output) => {',
    '      output.context.push(context);',
    '    },',
    '  }),',
    '};',
    '',
  ].join('\n');
}

/**
 * @description Whether a `GET /config` `plugin` list contains the bot's plugin. A
 * spec is a string or a `[spec, options]` tuple; OpenCode reports a path plugin as
 * a `file://` URL. Matched by file name, not by full path, because the server may
 * have been started by a process whose `DATA_DIR` resolved to a different spelling
 * of the same directory.
 */
export function checkHasOpenCodeCompactPlugin(pluginSpecs: unknown): boolean {
  if (!Array.isArray(pluginSpecs)) return false;
  return pluginSpecs.some((entry) => {
    const spec = Array.isArray(entry) ? entry[0] : entry;
    return typeof spec === 'string' && spec.endsWith(`/${openCodeCompactPluginFileName}`);
  });
}

/**
 * @description Add the plugin to an `OPENCODE_CONFIG_CONTENT` value, keeping
 * whatever the environment already put there. Returns `null` when the existing
 * value is not a JSON object: OpenCode would reject a value the bot can't parse
 * either, and overwriting it would silently drop the operator's own config.
 */
export function buildOpenCodeConfigContentWithPlugin(
  existing: string | undefined,
  pluginUrl: string,
): string | null {
  let config: Record<string, unknown> = {};
  if (existing?.trim()) {
    try {
      const parsed: unknown = JSON.parse(existing);
      if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return null;
      config = parsed as Record<string, unknown>;
    } catch {
      return null;
    }
  }
  const plugins = Array.isArray(config.plugin) ? config.plugin : [];
  return JSON.stringify({ ...config, plugin: [...plugins, pluginUrl] });
}

/**
 * @description Write the plugin file and return the env entries that load it into
 * an `opencode serve` about to start. Any failure returns `{}` and only logs: the
 * plugin improves a summary, it must never keep the server from starting.
 */
export function prepareOpenCodeCompactPluginEnv(
  dataDir: string,
  baseEnv: NodeJS.ProcessEnv,
): Record<string, string> {
  const pluginPath = path.join(dataDir, openCodeCompactPluginFileName);
  const configContent = buildOpenCodeConfigContentWithPlugin(
    baseEnv.OPENCODE_CONFIG_CONTENT,
    pathToFileURL(pluginPath).href,
  );
  if (configContent === null) {
    console.warn('[compact-plugin] OPENCODE_CONFIG_CONTENT is not a JSON object; the compaction plugin is not loaded');
    return {};
  }
  const tmpPath = `${pluginPath}.${process.pid}.${Date.now()}.tmp`;
  try {
    fs.mkdirSync(dataDir, { recursive: true });
    fs.writeFileSync(tmpPath, buildOpenCodeCompactPluginSource(getOpenCodeCompactPluginContext()));
    fs.renameSync(tmpPath, pluginPath);
  } catch (e) {
    console.warn(`[compact-plugin] cannot write ${pluginPath}:`, e);
    try { fs.unlinkSync(tmpPath); } catch { /* never written */ }
    return {};
  }
  return { OPENCODE_CONFIG_CONTENT: configContent };
}
